<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Payments table — an immutable audit log of every Razorpay payment event.
 *
 * Every payment is a discrete Razorpay Payment Link generated by admin.
 * There are no recurring subscriptions or auto-charges.
 *
 * Payment types:
 *   creation_upfront   → 50% of the editorial creation fee, before work begins
 *   creation_balance   → remaining 50%, after member approves the draft
 *   annual_maintenance → ₹3,000 + GST/yr, from the member's second year
 *   editorial_minor    → Minor Editorial Update ₹3,000 + GST
 *   editorial_major    → Major Editorial Revision ₹5,000 + GST
 *                         (also covers package tier upgrades at the same flat rate)
 *   legacy_commission  → In Memoriam commission ₹25,000 + GST (3 yrs included)
 *   legacy_continuation → In Memoriam continuation ₹3,000 + GST/yr after 3 yrs
 *
 * Webhook is the source of truth — never trust a client-side redirect.
 * Every status change from Razorpay is written here as a new event_type entry.
 *
 * GST handling: creation fees (Register) are GST-inclusive; all other charges
 * are +GST. The gst_inclusive flag per row drives invoice generation.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();

            // Who this payment belongs to.
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();

            // What this payment is for — polymorphic so it can link to an application,
            // a profile, or a legacy_profile.
            $table->nullableMorphs('payable');  // payable_type + payable_id

            // Type of payment (see docblock above).
            $table->string('payment_type');

            // Razorpay Payment Link details.
            $table->string('razorpay_payment_link_id')->nullable()->unique();
            $table->string('razorpay_payment_id')->nullable();  // Actual payment ID on capture.
            $table->string('razorpay_order_id')->nullable();

            // Amount in smallest currency unit (paise for INR).
            $table->unsignedBigInteger('amount_paise');

            // Whether the amount already includes GST or is exclusive of GST.
            $table->boolean('gst_inclusive')->default(false);

            // GST amount in paise (stored for invoice generation).
            $table->unsignedBigInteger('gst_paise')->default(0);

            // Payment link URL — sent to the member/commissioner.
            $table->string('payment_link_url')->nullable();

            // Current status as last seen from Razorpay.
            // 'created' | 'sent' | 'paid' | 'cancelled' | 'expired'
            $table->string('status')->default('created');

            // Raw Razorpay webhook payload (kept for dispute resolution).
            $table->json('razorpay_payload')->nullable();

            // Admin who generated this payment link.
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();

            // Expiry date of the payment link.
            $table->timestamp('expires_at')->nullable();
            $table->timestamp('paid_at')->nullable();

            // Description shown on the Razorpay payment page.
            $table->string('description')->nullable();

            $table->timestamps();

            $table->index('payment_type');
            $table->index('status');
            $table->index('user_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
