<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;

/**
 * Payment model — an immutable audit record for every Razorpay event.
 *
 * Every payment is a discrete Razorpay Payment Link, generated by the admin
 * and sent to the member. No auto-charges or recurring billing.
 *
 * The Razorpay webhook is the authoritative source of truth for payment status.
 * Never trust a client-side redirect as confirmation that money was received.
 *
 * Amount is stored in paise (smallest Indian currency unit) to avoid
 * floating-point rounding issues. GST flags enable accurate invoice generation.
 */
class Payment extends Model
{
    protected $fillable = [
        'user_id',
        'payable_type',
        'payable_id',
        'payment_type',
        'razorpay_payment_link_id',
        'razorpay_payment_id',
        'razorpay_order_id',
        'amount_paise',
        'gst_inclusive',
        'gst_paise',
        'payment_link_url',
        'status',
        'razorpay_payload',
        'created_by',
        'expires_at',
        'paid_at',
        'description',
    ];

    protected function casts(): array
    {
        return [
            'gst_inclusive'     => 'boolean',
            'razorpay_payload'  => 'array',
            'expires_at'        => 'datetime',
            'paid_at'           => 'datetime',
        ];
    }

    // ── Payment type constants ────────────────────────────────────────────────

    const TYPE_CREATION_UPFRONT     = 'creation_upfront';
    const TYPE_CREATION_BALANCE     = 'creation_balance';
    const TYPE_ANNUAL_MAINTENANCE   = 'annual_maintenance';
    const TYPE_EDITORIAL_MINOR      = 'editorial_minor';
    const TYPE_EDITORIAL_MAJOR      = 'editorial_major';
    const TYPE_LEGACY_COMMISSION    = 'legacy_commission';
    const TYPE_LEGACY_CONTINUATION  = 'legacy_continuation';

    // ── Relationships ─────────────────────────────────────────────────────────

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function payable(): MorphTo
    {
        return $this->morphTo();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public function getAmountRupeesAttribute(): float
    {
        return $this->amount_paise / 100;
    }

    public function getGstRupeesAttribute(): float
    {
        return $this->gst_paise / 100;
    }

    public function isPaid(): bool
    {
        return $this->status === 'paid';
    }
}
